name: next-js-dev
services:
  web:
    depends_on: 
    - db
    image: next-js-dev
    container_name: next-js-dev-web
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    # environment: 
      # - DB_URL: mongodb://db/tasked
    env_file:
      - .env.local
    command: npm run dev
    develop:
      watch:
        # dependencies
        - path: package.json
          action: rebuild
        - path: package-lock.json
          action: rebuild
        # app
        - path: .
          target: /app
          action: sync
  
  db:
    image: mongo:latest
    container_name: next-js-dev-db
    ports:
      # default local mongodb port 27017
      - 27017:27017
    volumes:
      # mount volume "tasked" inside the container at /data/db directory
      - tasked:/data/db

# volumes
volumes:
  tasked: