apiVersion: v1
kind: Namespace
metadata:
  name: mern-js-local

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mern-js-local
  namespace: mern-js-local
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi

---
apiVersion: v1
kind: LimitRange
metadata:
  name: mern-js-local
  namespace: mern-js-local
spec:
  limits:
    - default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      type: Container
