name: mern-js-backend-dev
services:
  api:
    depends_on: 
    - db
    image: mern-js-backend-dev
    container_name: mern-js-backend-dev-api
    build: 
      context: ../
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:8000"
    # environment: 
    #   DB_URL: mongodb://db/anime
    env_file:
      - ../.env.local
    # command: npm run dev
    develop:
      watch:
        # dependencies
        - path: package.json
          action: rebuild
        - path: package-lock.json
          action: rebuild
        # app
        - path: .
          target: /app
          action: sync
  
  db:
    image: mongo:latest
    container_name: mern-js-backend-dev-db
    ports:
      # default local mongodb port 27017
      - 27017:27017
    volumes:
      # mount volume "anime" inside the container at /data/db directory
      - anime:/data/db

# define the volumes to be used by the services
volumes:
  anime:
