FROM node:22-alpine

# add user and group
RUN addgroup app && adduser -S -G app app
USER app

WORKDIR /app
ENV CHOKIDAR_USEPOLLING=true
COPY package*.json ./

# set permissions
USER root
RUN chown -R app:app .
USER app

RUN npm install
COPY . .

EXPOSE 5173
CMD ["npm", "run", "dev"]