name: mern-js-frontend
services:
  web:
    image: mern-js-frontend
    container_name: mern-js-frontend-web
    build: 
      context: ../
      dockerfile: docker/Dockerfile.prod
    ports:
      # - "4173:4173"
      - "4000:4000"
    env_file:
      - ../.env